# Docker compose for deploying spring boot application into tomcat container

version: '3.7'

services:
  huellitas-backend:
    container_name: huellitas-backend
    image: huellitas-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    restart: always