# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: pg_container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ncapasProject
      POSTGRES_PASSWORD: ncapasPassword
      POSTGRES_DB: ncapasDB

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"


##    restart: always

##c Servers > Create > Server

## name my_db

## ==> Connection

## Host name : pg_container

## Port : 5432

## Username ncapasProject

## Password ncapasPassword ---> Save
